name: app_movil
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.0+3
  path: ^1.8.3
  http: ^1.2.2
  provider: ^6.0.0
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  shared_preferences: ^2.0.6
  percent_indicator: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: ^5.0.15
  build_runner: ^2.1.7
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true